### ISSUE TITLE
Disable scrolling when modal is open

### ISSUE THREAD

**Issue by wobsoriano** [wobsoriano/poke95#2]
As the title says, when you open a pokemon info modal, you are still able to scroll in the background.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/13049130/94991346-1c7b6380-05b5-11eb-8f9b-4f31227d7222.gif)

**Comment by geeks5551** [comment]
hey can I contribute to the disabling scrolling when modal is open?

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/poke95/pull/5
